/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Desktop;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lucas
 */
public class fAccueil extends javax.swing.JFrame {
    private fGameplaySolo fGameplaySolo;
    private boolean duo; //definie si l'utilisateur joue seul ou avec un copain
    private final GraphicsDevice device; //recupere les specificites de l'ecran

    public fAccueil() {
        initComponents();
        device=GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lTitre = new javax.swing.JLabel();
        bSolo = new javax.swing.JButton();
        b2Joueurs = new javax.swing.JButton();
        bRegles = new javax.swing.JButton();
        bExit = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 0));

        jPanel1.setPreferredSize(new java.awt.Dimension(849, 543));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTitre.setBackground(new java.awt.Color(204, 204, 0));
        lTitre.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        lTitre.setForeground(new java.awt.Color(204, 204, 0));
        lTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitre.setText("Jeu du Piquet");
        lTitre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 3));
        jPanel2.add(lTitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 722, 122));

        bSolo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bSolo.setForeground(new java.awt.Color(0, 0, 204));
        bSolo.setText("Solo");
        bSolo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 3));
        bSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSoloActionPerformed(evt);
            }
        });
        jPanel2.add(bSolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 169, 158, 95));

        b2Joueurs.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2Joueurs.setForeground(new java.awt.Color(204, 0, 0));
        b2Joueurs.setText("Duo");
        b2Joueurs.setToolTipText("");
        b2Joueurs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 3));
        b2Joueurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2JoueursActionPerformed(evt);
            }
        });
        jPanel2.add(b2Joueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 291, 158, 95));

        bRegles.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bRegles.setText("Règles");
        bRegles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bRegles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReglesActionPerformed(evt);
            }
        });
        jPanel2.add(bRegles, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 412, 158, 95));

        bExit.setBackground(new java.awt.Color(204, 0, 51));
        bExit.setText("Quitter");
        bExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 2));
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        jPanel2.add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 105, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSoloActionPerformed
        duo=false;
        fGameplaySolo=new fGameplaySolo(duo);
        device.setFullScreenWindow(fGameplaySolo);//met en plein ecran
        fGameplaySolo.setVisible(true);
    }//GEN-LAST:event_bSoloActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void b2JoueursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2JoueursActionPerformed
        duo=true;
        fGameplaySolo=new fGameplaySolo(duo); 
        device.setFullScreenWindow(fGameplaySolo);//met en plein ecran
        fGameplaySolo.setVisible(true); 
    }//GEN-LAST:event_b2JoueursActionPerformed

    private void bReglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReglesActionPerformed
    try{
        Desktop.getDesktop().browse(new URI("https://fr.wikipedia.org/wiki/Piquet_(jeu_de_cartes)#:~:text=Chaque%20joueur%20tire%20une%20carte,que%20chacun%20en%20ait%20douze."));
    }catch (URISyntaxException e) {
        e.printStackTrace();
    }catch (IOException ex) {
        Logger.getLogger(fAccueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bReglesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2Joueurs;
    private javax.swing.JToggleButton bExit;
    private javax.swing.JButton bRegles;
    private javax.swing.JButton bSolo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lTitre;
    // End of variables declaration//GEN-END:variables
}
