/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import piquetbarreauandre.Jeu;
import piquetbarreauandre.Joueur;
import piquetbarreauandre.JoueurOrdinateur;

/**
 *
 * @author lucas
 */
public class fGameplaySolo extends javax.swing.JFrame {

    private String pseudo;
    private int etape=0;
    private int compt;
    private int choix;
    private boolean continuer=false; //empeche l'execution du switch dans les etapes de navigation
    private boolean partie; //vrai-> duo / faux-> solo
    private boolean recommencer=false; //vrai si le joueur veu en refaire une
    private Joueur joueur1;
    private Joueur joueur2;
    private Jeu jeu;
    private ArrayList<JLabel> bMainJoueur1;
    private ArrayList<JLabel> bMainJoueur2;
    private Random ran= new Random();
    private ImageIcon icon;
    public fGameplaySolo(boolean duo) {
        super();
        initComponents();
        this.partie=duo;
        pMainJoueur1.setVisible(false);
        pMainJoueur2.setVisible(false);
        pCarteJouee.setVisible(true);
        JLabel a[] = new JLabel[]{bMain1,bMain2,bMain3,bMain4,bMain5,bMain6,bMain7,bMain8,bMain9,bMain10,bMain11,bMain12};
        bMainJoueur1 = new ArrayList(Arrays.asList(a));  
        JLabel b[] = new JLabel[]{bMain13,bMain14,bMain15,bMain16,bMain17,bMain18,bMain19,bMain20,bMain21,bMain22,bMain23,bMain24};
        bMainJoueur2 = new ArrayList(Arrays.asList(b));        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        pCarteJouee = new javax.swing.JPanel();
        lCarteJou2 = new javax.swing.JLabel();
        lCarteJou1 = new javax.swing.JLabel();
        pMainJoueur1 = new javax.swing.JPanel();
        bMain3 = new javax.swing.JLabel();
        bMain6 = new javax.swing.JLabel();
        bMain7 = new javax.swing.JLabel();
        bMain9 = new javax.swing.JLabel();
        bMain11 = new javax.swing.JLabel();
        bMain1 = new javax.swing.JLabel();
        bMain2 = new javax.swing.JLabel();
        bMain4 = new javax.swing.JLabel();
        bMain5 = new javax.swing.JLabel();
        bMain8 = new javax.swing.JLabel();
        bMain10 = new javax.swing.JLabel();
        bMain12 = new javax.swing.JLabel();
        pMainJoueur2 = new javax.swing.JPanel();
        bMain14 = new javax.swing.JLabel();
        bMain18 = new javax.swing.JLabel();
        bMain19 = new javax.swing.JLabel();
        bMain21 = new javax.swing.JLabel();
        bMain22 = new javax.swing.JLabel();
        bMain23 = new javax.swing.JLabel();
        bMain13 = new javax.swing.JLabel();
        bMain15 = new javax.swing.JLabel();
        bMain16 = new javax.swing.JLabel();
        bMain17 = new javax.swing.JLabel();
        bMain20 = new javax.swing.JLabel();
        bMain24 = new javax.swing.JLabel();
        infoJoueur3 = new javax.swing.JPanel();
        lScore2 = new javax.swing.JLabel();
        lScoreOrdiVal = new javax.swing.JLabel();
        lPseudoOrdi = new javax.swing.JLabel();
        infoJoueur2 = new javax.swing.JPanel();
        lScore = new javax.swing.JLabel();
        lScoreJoueur1Val = new javax.swing.JLabel();
        lPseudo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lInstructions = new javax.swing.JLabel();
        jPseudo = new javax.swing.JTextField();
        bNavigation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PartieSolo");
        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(1000, 857));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1000, 857));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fond.jpg"))); // NOI18N
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 1180, 1060));

        pCarteJouee.setOpaque(false);

        lCarteJou2.setBackground(new java.awt.Color(255, 255, 255));
        lCarteJou2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lCarteJou2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCarteJou2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lCarteJou2.setOpaque(true);
        lCarteJou2.setPreferredSize(new java.awt.Dimension(71, 96));

        lCarteJou1.setBackground(new java.awt.Color(255, 255, 255));
        lCarteJou1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lCarteJou1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCarteJou1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lCarteJou1.setOpaque(true);
        lCarteJou1.setPreferredSize(new java.awt.Dimension(71, 96));

        javax.swing.GroupLayout pCarteJoueeLayout = new javax.swing.GroupLayout(pCarteJouee);
        pCarteJouee.setLayout(pCarteJoueeLayout);
        pCarteJoueeLayout.setHorizontalGroup(
            pCarteJoueeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCarteJoueeLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(pCarteJoueeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lCarteJou1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(lCarteJou2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        pCarteJoueeLayout.setVerticalGroup(
            pCarteJoueeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCarteJoueeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCarteJou2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(lCarteJou1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLayeredPane1.setLayer(pCarteJouee, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(pCarteJouee, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 170, 270));

        pMainJoueur1.setOpaque(false);
        pMainJoueur1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bMain3.setBackground(new java.awt.Color(255, 255, 255));
        bMain3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain3.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain3.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain3.setOpaque(true);
        bMain3.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur1.add(bMain3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 70, 100));

        bMain6.setBackground(new java.awt.Color(255, 255, 255));
        bMain6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain6.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain6.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain6.setOpaque(true);
        bMain6.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur1.add(bMain6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 70, 100));

        bMain7.setBackground(new java.awt.Color(255, 255, 255));
        bMain7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain7.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain7.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain7.setOpaque(true);
        bMain7.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur1.add(bMain7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 70, 100));

        bMain9.setBackground(new java.awt.Color(255, 255, 255));
        bMain9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain9.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain9.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain9.setOpaque(true);
        bMain9.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur1.add(bMain9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 70, 100));

        bMain11.setBackground(new java.awt.Color(255, 255, 255));
        bMain11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain11.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain11.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain11.setOpaque(true);
        bMain11.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur1.add(bMain11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 70, 100));

        bMain1.setBackground(new java.awt.Color(255, 255, 255));
        bMain1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain1.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain1.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain1.setOpaque(true);
        bMain1.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur1.add(bMain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 100));

        bMain2.setBackground(new java.awt.Color(255, 255, 255));
        bMain2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain2.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain2.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain2.setOpaque(true);
        bMain2.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur1.add(bMain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 70, 100));

        bMain4.setBackground(new java.awt.Color(255, 255, 255));
        bMain4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain4.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain4.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain4.setOpaque(true);
        bMain4.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur1.add(bMain4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 70, 100));

        bMain5.setBackground(new java.awt.Color(255, 255, 255));
        bMain5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain5.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain5.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain5.setOpaque(true);
        bMain5.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur1.add(bMain5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 70, 100));

        bMain8.setBackground(new java.awt.Color(255, 255, 255));
        bMain8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain8.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain8.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain8.setOpaque(true);
        bMain8.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur1.add(bMain8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 70, 100));

        bMain10.setBackground(new java.awt.Color(255, 255, 255));
        bMain10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain10.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain10.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain10.setOpaque(true);
        bMain10.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur1.add(bMain10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 70, 100));

        bMain12.setBackground(new java.awt.Color(255, 255, 255));
        bMain12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain12.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain12.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain12.setOpaque(true);
        bMain12.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur1.add(bMain12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 70, 100));

        jLayeredPane1.setLayer(pMainJoueur1, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(pMainJoueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 990, 160));
        pMainJoueur1.getAccessibleContext().setAccessibleParent(jLayeredPane1);

        pMainJoueur2.setOpaque(false);
        pMainJoueur2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bMain14.setBackground(new java.awt.Color(255, 255, 255));
        bMain14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain14.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain14.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain14.setOpaque(true);
        bMain14.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur2.add(bMain14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 70, 100));

        bMain18.setBackground(new java.awt.Color(255, 255, 255));
        bMain18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain18.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain18.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain18.setOpaque(true);
        bMain18.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur2.add(bMain18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 70, 100));

        bMain19.setBackground(new java.awt.Color(255, 255, 255));
        bMain19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain19.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain19.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain19.setOpaque(true);
        bMain19.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur2.add(bMain19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 70, 100));

        bMain21.setBackground(new java.awt.Color(255, 255, 255));
        bMain21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain21.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain21.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain21.setOpaque(true);
        bMain21.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur2.add(bMain21, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 70, 100));

        bMain22.setBackground(new java.awt.Color(255, 255, 255));
        bMain22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain22.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain22.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain22.setOpaque(true);
        bMain22.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur2.add(bMain22, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 70, 100));

        bMain23.setBackground(new java.awt.Color(255, 255, 255));
        bMain23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain23.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain23.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain23.setOpaque(true);
        bMain23.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur2.add(bMain23, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 70, 100));

        bMain13.setBackground(new java.awt.Color(255, 255, 255));
        bMain13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain13.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain13.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain13.setOpaque(true);
        bMain13.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur2.add(bMain13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 100));

        bMain15.setBackground(new java.awt.Color(255, 255, 255));
        bMain15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain15.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain15.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain15.setOpaque(true);
        bMain15.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur2.add(bMain15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 70, 100));

        bMain16.setBackground(new java.awt.Color(255, 255, 255));
        bMain16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain16.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain16.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain16.setOpaque(true);
        bMain16.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur2.add(bMain16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 70, 100));

        bMain17.setBackground(new java.awt.Color(255, 255, 255));
        bMain17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain17.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain17.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain17.setOpaque(true);
        bMain17.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur2.add(bMain17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 70, 100));

        bMain20.setBackground(new java.awt.Color(255, 255, 255));
        bMain20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain20.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain20.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain20.setOpaque(true);
        bMain20.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur2.add(bMain20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 70, 100));

        bMain24.setBackground(new java.awt.Color(255, 255, 255));
        bMain24.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bMain24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMain24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bMain24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMain24.setMaximumSize(new java.awt.Dimension(71, 96));
        bMain24.setMinimumSize(new java.awt.Dimension(71, 96));
        bMain24.setOpaque(true);
        bMain24.setPreferredSize(new java.awt.Dimension(71, 96));
        pMainJoueur2.add(bMain24, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 70, 100));

        jLayeredPane1.setLayer(pMainJoueur2, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(pMainJoueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 990, 160));

        infoJoueur3.setBackground(new java.awt.Color(153, 153, 255));
        infoJoueur3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        infoJoueur3.setForeground(new java.awt.Color(255, 255, 0));

        lScore2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lScore2.setForeground(new java.awt.Color(255, 255, 51));
        lScore2.setText("Score :");

        lScoreOrdiVal.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lScoreOrdiVal.setForeground(new java.awt.Color(255, 255, 0));
        lScoreOrdiVal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lScoreOrdiVal.setText("0");

        lPseudoOrdi.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lPseudoOrdi.setForeground(new java.awt.Color(255, 255, 51));
        lPseudoOrdi.setText("Ordinateur");

        javax.swing.GroupLayout infoJoueur3Layout = new javax.swing.GroupLayout(infoJoueur3);
        infoJoueur3.setLayout(infoJoueur3Layout);
        infoJoueur3Layout.setHorizontalGroup(
            infoJoueur3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoJoueur3Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lPseudoOrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lScore2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lScoreOrdiVal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        infoJoueur3Layout.setVerticalGroup(
            infoJoueur3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoJoueur3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoJoueur3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lScore2)
                    .addComponent(lPseudoOrdi)
                    .addComponent(lScoreOrdiVal))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(infoJoueur3, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(infoJoueur3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        infoJoueur2.setBackground(new java.awt.Color(153, 153, 255));
        infoJoueur2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        infoJoueur2.setForeground(new java.awt.Color(255, 255, 0));

        lScore.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lScore.setForeground(new java.awt.Color(255, 255, 0));
        lScore.setText("Score :");

        lScoreJoueur1Val.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lScoreJoueur1Val.setForeground(new java.awt.Color(255, 255, 0));
        lScoreJoueur1Val.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lScoreJoueur1Val.setText("0");

        lPseudo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lPseudo.setForeground(new java.awt.Color(255, 255, 0));
        lPseudo.setText("Joueur 1");

        javax.swing.GroupLayout infoJoueur2Layout = new javax.swing.GroupLayout(infoJoueur2);
        infoJoueur2.setLayout(infoJoueur2Layout);
        infoJoueur2Layout.setHorizontalGroup(
            infoJoueur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoJoueur2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(lScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lScoreJoueur1Val, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        infoJoueur2Layout.setVerticalGroup(
            infoJoueur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoJoueur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lScoreJoueur1Val)
                .addComponent(lPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.setLayer(infoJoueur2, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(infoJoueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 780, 610, 60));

        jPanel1.setOpaque(false);

        lInstructions.setBackground(new java.awt.Color(153, 153, 255));
        lInstructions.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lInstructions.setForeground(new java.awt.Color(255, 255, 0));
        lInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lInstructions.setText("Entrez votre pseudo");
        lInstructions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        lInstructions.setOpaque(true);

        jPseudo.setBackground(new java.awt.Color(153, 204, 255));
        jPseudo.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jPseudo.setForeground(new java.awt.Color(255, 255, 0));
        jPseudo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPseudo.setText("Joueur 1");
        jPseudo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        jPseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPseudoActionPerformed(evt);
            }
        });

        bNavigation.setBackground(new java.awt.Color(255, 255, 255));
        bNavigation.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        bNavigation.setForeground(new java.awt.Color(0, 153, 0));
        bNavigation.setText("Valider");
        bNavigation.setActionCommand("");
        bNavigation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        bNavigation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNavigationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(bNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 370, 220));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jPseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPseudoActionPerformed

    }//GEN-LAST:event_jPseudoActionPerformed

    private void bNavigationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNavigationActionPerformed

        bNavigation.setEnabled(false);
        if (etape==0){
            lInstructions.setText("On y va ?");
            bNavigation.setText("Lancer partie");
            if(!recommencer){ //ce test permet d'empecher qu'a chaque match retour l'ordi recreer des instances d'objets
                
                jeu = new Jeu();
                pseudo=jPseudo.getText();

                
                while((((pseudo.equals("Ordinateur"))) || pseudo.equals(""))||(pseudo==null)){ //empeche que l'utilisateur ferme la fenetre sans rentrer son nom ou de rentrer un nom interdit
                    JOptionPane.showMessageDialog(this,"Nom incorrect");
                    try{
                        pseudo=JOptionPane.showInputDialog(this, "Entrez votre pseudo Joueur 1");
                    }catch(java.lang.NullPointerException e){
                        JOptionPane.showMessageDialog(this,"Veuillez entrer un nom.");
                        pseudo="";
                    }  
                } 
                joueur1=new Joueur(pseudo);
                lPseudo.setText(joueur1.getNom());                 
                if (partie){ //creer le joueur2 en mode utilisateur si le mode duo est selectionne
                    while((pseudo.equals(joueur1.getNom())) ||(pseudo.equals(joueur1.getNom()+" ")) || (pseudo.equals(" "+joueur1.getNom()+" ")) ||((pseudo.equals("Ordinateur"))|| pseudo.equals(""))||(pseudo==null)){ //empeche que l'utilisateur ferme la fenetre sans rentrer son nom ou de rentrer un nom interdit
                        JOptionPane.showMessageDialog(this, "Nom incorrect");
                        try{
                            pseudo=JOptionPane.showInputDialog(this, "Entrez votre pseudo Joueur 2");
                        }catch(java.lang.NullPointerException e){
                            JOptionPane.showMessageDialog(this,"Veuillez entrer un nom.");
                        }                   
                    }                 
                    joueur2= new Joueur(pseudo);
                    lPseudoOrdi.setText(pseudo);
                }else{
                    joueur2=new JoueurOrdinateur();
                }
            }
            jeu.melange();
            bNavigation.setEnabled(true);
            jPseudo.setVisible(false);
        }
        if (etape==1){
            bNavigation.setText("Continuer");
            lInstructions.setText("Distribution");
            compt=1; //compteur de tour
            boolean continuer=true;
            jeu.distribue(joueur1, joueur2);
            if(partie){ //affiche les mains des joueurs avec un laps de temps procurer par les JOptionPane
                JOptionPane.showMessageDialog(this,"Main de "+joueur1.getNom());
                pMainJoueur1.setVisible(true);
                joueur1.afficherMain(bMainJoueur1);
                JOptionPane.showMessageDialog(this,"Vue ?"); //de cette maniere les joueurs ne voient que leurs mains
                pMainJoueur1.setVisible(false);
                JOptionPane.showMessageDialog(this,"Main de "+joueur2.getNom());
                pMainJoueur2.setVisible(true);
                joueur2.afficherMain(bMainJoueur2);           
                JOptionPane.showMessageDialog(this,"Vue ?");
                pMainJoueur2.setVisible(false);
            }else{ //seul la main du joueur1 est interessante dans le cas d'une partie solo
                pMainJoueur1.setVisible(true);
                joueur1.afficherMain(bMainJoueur1);
            }
            bNavigation.setEnabled(true);
        }


        if(continuer){
            choix=ran.nextInt(2);//genere aleatoirement 0 ou 1 pour definir l'ordre
            switch(0){ 
                case 0 :
                    if(etape==2){
                        
                        /********************
                            PHASE D'ECART
                        *********************/
                        
                        lInstructions.setText("Phase d'Ecart");
                        if (partie){
                            
                            //phase d'ecart su joueur1
                            JOptionPane.showMessageDialog(this,"Phase d'écart de "+joueur1.getNom());
                            pMainJoueur1.setVisible(true); 
                            joueur1.afficherMain(bMainJoueur1); //affiche sa main
                            joueur1.ecarte(jeu,bMainJoueur1, this, icon); //lance la methode d'ecart
                            pMainJoueur1.setVisible(false);
                            joueur1.talonCheck(true,this,jeu); //seul le premier joueur peut consulter le talon
                            
                            //phase d'ecart joueur2
                            JOptionPane.showMessageDialog(this,"Phase d'écart de "+joueur2.getNom());
                            pMainJoueur2.setVisible(true);
                            joueur2.afficherMain(bMainJoueur2);
                            joueur2.ecarte(jeu,bMainJoueur2, this, icon);
                            pMainJoueur2.setVisible(false);                            
                            
                        }else{
                            //dans le cas du solo 
                            joueur1.ecarte(jeu,bMainJoueur1, this, icon);
                            joueur1.talonCheck(true,this,jeu);
                            joueur2.ecarte(jeu,bMainJoueur2, this, icon); //cette methode est surchargee et automatique dans JoueurOrdinateur 
                        }                  
                        bNavigation.setEnabled(true);
                    }
                    if (etape==3){

                        /********************
                           PHASE D'ANNONCE
                        *********************/
                        
                        lInstructions.setText("Phase d'Annonce");
                        joueur1.infoMain(this); //calcul les combinaisons des deux joueurs
                        joueur2.infoMain(this);
                        jeu.annonce(joueur1,joueur2,this,lScoreJoueur1Val,lScoreOrdiVal); //compare et affiche les resultats
                        lScoreJoueur1Val.setText(String.valueOf(joueur1.getScore())); //mise a jour des scores
                        lScoreOrdiVal.setText(String.valueOf(joueur2.getScore()));
                        bNavigation.setEnabled(true);
                    }
                    if (etape==4){
                        
                        /********************
                            PHASE DE JEU
                        *********************/                        
                        
                        lInstructions.setText("Phase de Jeu");
                        pMainJoueur1.setVisible(true);
                        if (partie){pMainJoueur2.setVisible(true);} //permet l'affichage de la main du joueur2 dans le cas d'un duo
                        while (compt<13){ //boucle de jeu en 12 tours representants les 12 plis !
                            jeu.pli(joueur1,joueur2,bMainJoueur1,bMainJoueur2, this,lCarteJou1,lCarteJou2,choix,partie,pMainJoueur1,pMainJoueur2);
                            choix=2; //permet d'empecher que le meme joueur joue en premier chaque tour cf Jeu.pli
                            compt++;
                        }
                        bNavigation.setEnabled(true);
                    }
                    break;
                    
                case 1 : //Meme principe simplement ici joueur2 a l'initiative
                    if(etape==2){
                        lInstructions.setText("Phase d'Ecart");
                        if (partie){
                            JOptionPane.showMessageDialog(this,"Phase d'écart de "+joueur2.getNom());
                            pMainJoueur2.setVisible(true);
                            joueur2.afficherMain(bMainJoueur2);
                            joueur2.ecarte(jeu,bMainJoueur2, this, icon);
                            pMainJoueur2.setVisible(false);
                            joueur2.talonCheck(true,this,jeu);
                            
                            JOptionPane.showMessageDialog(this,"Phase d'écart de "+joueur1.getNom());
                            pMainJoueur1.setVisible(true);
                            joueur1.afficherMain(bMainJoueur1);
                            joueur1.ecarte(jeu,bMainJoueur1, this, icon);
                            pMainJoueur1.setVisible(false);                            
                            
                        }else{
                            joueur2.ecarte(jeu,bMainJoueur2, this, icon);
                            joueur2.talonCheck(true,this,jeu);
                            joueur1.ecarte(jeu,bMainJoueur1, this, icon);
                        }                  
                        bNavigation.setEnabled(true);
                    }
                    if (etape==3){
                        lInstructions.setText("Phase d'Annonce");
                        joueur2.infoMain(this);
                        joueur1.infoMain(this);
                        jeu.annonce(joueur2,joueur1,this,lScoreOrdiVal,lScoreJoueur1Val);
                        bNavigation.setEnabled(true);
                    }
                    if (etape==4){
                        lInstructions.setText("Phase de Jeu");
                        pMainJoueur1.setVisible(true);
                        pMainJoueur2.setVisible(true);
                        while (compt<13){
                            jeu.pli(joueur1,joueur2,bMainJoueur1,bMainJoueur2, this,lCarteJou2,lCarteJou1,choix,partie,pMainJoueur1,pMainJoueur2);
                            choix=2; //permet d'empecher que le meme joueur joue en premier chaque tour
                            compt++;
                        }
                        bNavigation.setEnabled(true);
                    }
                    break;
                }
        }
        
        /********************
            FIN DE MANCHE
        *********************/
        
        if (etape==5){
            lInstructions.setText("Fin de Manche");
            joueur2.setScore(joueur2.getPlis()); //on augmente le score des joueurs en fonction du nombre de plis qu'ils ont gagne
            joueur1.setScore(joueur1.getPlis());
            joueur2.setScore_total(joueur2.getScore()); //on set le score total des deux joueurs pour avoir notre champion
            joueur1.setScore_total(joueur1.getScore());
            lScoreJoueur1Val.setText(String.valueOf(joueur1.getScore_total())); //on affiche les scores sur les labels
            lScoreOrdiVal.setText(String.valueOf(joueur2.getScore_total()));
            etape=jeu.finDeManche(joueur1, joueur2,this); //on lance la methode finDeManche :
            if(etape!=0){                                       //si son retour est different de 0 on ferme le jeu
                System.exit(0);
           }else{                                               //sinon on met en place la reinitialisation
                recommencer=true;
                for(int i=0;i<bMainJoueur1.size();i++){ //on reactive tous les labels
                    bMainJoueur1.get(i).setEnabled(true);
                    bMainJoueur2.get(i).setEnabled(true);
                }
                pMainJoueur1.setVisible(false); //on cache les mains des joueurs
                pMainJoueur2.setVisible(false);
                bNavigation.setEnabled(true);
            }
        }        
        if (etape==1){ //permet de lancer l'etape du switch qui defini qui joue en premier, sans cette etape le switch se lancait sans crier gare
            continuer=true;
        }
        etape++;
    }//GEN-LAST:event_bNavigationActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bMain1;
    private javax.swing.JLabel bMain10;
    private javax.swing.JLabel bMain11;
    private javax.swing.JLabel bMain12;
    private javax.swing.JLabel bMain13;
    private javax.swing.JLabel bMain14;
    private javax.swing.JLabel bMain15;
    private javax.swing.JLabel bMain16;
    private javax.swing.JLabel bMain17;
    private javax.swing.JLabel bMain18;
    private javax.swing.JLabel bMain19;
    private javax.swing.JLabel bMain2;
    private javax.swing.JLabel bMain20;
    private javax.swing.JLabel bMain21;
    private javax.swing.JLabel bMain22;
    private javax.swing.JLabel bMain23;
    private javax.swing.JLabel bMain24;
    private javax.swing.JLabel bMain3;
    private javax.swing.JLabel bMain4;
    private javax.swing.JLabel bMain5;
    private javax.swing.JLabel bMain6;
    private javax.swing.JLabel bMain7;
    private javax.swing.JLabel bMain8;
    private javax.swing.JLabel bMain9;
    private javax.swing.JButton bNavigation;
    private javax.swing.JPanel infoJoueur2;
    private javax.swing.JPanel infoJoueur3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPseudo;
    private javax.swing.JLabel lCarteJou1;
    private javax.swing.JLabel lCarteJou2;
    private javax.swing.JLabel lInstructions;
    private javax.swing.JLabel lPseudo;
    private javax.swing.JLabel lPseudoOrdi;
    private javax.swing.JLabel lScore;
    private javax.swing.JLabel lScore2;
    private javax.swing.JLabel lScoreJoueur1Val;
    private javax.swing.JLabel lScoreOrdiVal;
    private javax.swing.JPanel pCarteJouee;
    private javax.swing.JPanel pMainJoueur1;
    private javax.swing.JPanel pMainJoueur2;
    // End of variables declaration//GEN-END:variables
}
